### ISSUE TITLE
res101_faster_rcnn_iter_110000.ckpt.meta

### ISSUE THREAD

**Issue by Jai-wei** [dBeker/Faster-RCNN-TensorFlow-Python3#70]
File "demo.py", line 123, in <module>
    'our server and place them properly?').format(tfmodel + '.meta'))
OSError: output\res101\voc_2007_trainval+voc_2012_trainval\default\res101_faster_rcnn_iter_110000.ckpt.meta not found.
Did you download the proper networks from our server and place them properly?

why？

**Comment by wjwABCDEFG** [comment]
hello, I met the same problem, could you please tell me how to solve?

**Comment by morpheusthewhite** [comment]
You don't need to run it

**Comment by wjwABCDEFG** [comment]
thanks a lot , I had traced the cause of trouble .

**Comment by GhaithAlrefai** [comment]
How did you solve this issue?

**Comment by wjwABCDEFG** [comment]
> How did you solve this issue?
If you can understand Chinese you can see this blog: 
          https://blog.csdn.net/qq_41895190/article/details/82877883

First:you should run train.py then you can get a lot of file in ./default\voc_2007_trainval\default

Second:because of the default config,you only can get the 40000 iters model, copy four files(names include 40000) to ./output\vgg16\voc_2007_trainval+voc_2012_trainval\default\ (you should create the path by yourself, and if you train in res101, change vgg16 to res101)

Third:edit demo.py lines 108 change the parameter default='vgg16'(if you train in res101, you don't need to change)

Fourth:edit demo.py lines 39
old:NETS = {'vgg16': ('vgg16_faster_rcnn_iter_70000.ckpt',), 'res101':
 ('res101_faster_rcnn_iter_110000.ckpt',)}
new:change the 70000/110000 to 4000(its depend on the second step)

then you can run demo.py

**Comment by GhaithAlrefai** [comment]
Thanks for the answer, it worked for me
Training the data using CPU takes long time, 5000 iterations took almost 24
I reduced the number of the training iterations to 2000, but the model files wasn't created, I figured out that the minimum iterations is 5000
My next step is to label my dataset and pass it to the algorithm
